### ISSUE TITLE
nvcr.io部分镜像不能下载，提示格式错误

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [imdingtalk/image-mirror#516]
提示格式错误镜像为：nvcr.io/nvidia/k8s/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04

**Comment by imdingtalk** [comment]
已经解决 https://github.com/imdingtalk/image-mirror/commit/88ac19549e9b65abaf32c4225674ceb3561f7148
