### ISSUE TITLE
[ERROR] source error: unable to retrieve auth token: invalid username/password: unauthorized:

### ISSUE THREAD

**Issue by siruoren** [imdingtalk/image-mirror#87]
FORK REPO AND CONFIG FINISHED,SYNC ERROR!

source error: unable to retrieve auth token: invalid username/password: unauthorized: incorrect username or password. Now

**Comment by imdingtalk** [comment]
@siruoren 目标仓库的密码目前不支持特殊字符，更新下目标仓库的密码试试

**Comment by siruoren** [comment]
全小写字母加数字也不行

**Comment by imdingtalk** [comment]
> 全小写字母加数字也不行

更新了  同步下代码吧，dockerhub即使公开仓库也需要鉴权

**Comment by siruoren** [comment]
可以了，感谢大佬
